import React from 'react';

export default function AboutUniversity() {
  return (
    <div className="max-w-7xl mx-auto px-4 py-12">
      <div className="section-title-box">ABOUT UNIVERSITY</div>
      <div className="content-card mt-4 space-y-6 text-slate-700 text-sm leading-relaxed">
        <p>
          Government College University Hyderabad is one of Pakistan's oldest and prime educational institutions. Its genesis dates back to 1st October 1917, with the title of "Sindh National Arts College Hyderabad" having being contemplated by the International Theosophical Society. The crucial role in running the International Theosophical Society was played by its second president, Dr. Annie Besant, a well-known educationist, orator, political and social figure of the undivided Indian sub-continent. Another famous figure Dr. Ernest Egerton Wood, the secretary to National Educational Trust, continued "National Educational Movement" activities. He appealed through the newspapers for the establishment of new educational institutes in India.
        </p>
        <p>
          Since there was no college in Hyderabad Sindh, the students who wanted to continue higher education had to go to far off cities like Bombay. The first response of enormous contribution appeared from a youth of Sindh with a donation of Rs. 20,000/- on a condition to establish a college in Hyderabad Sindh. Another important figure among the city's aristocracy was Diwan Dayaram Gidumal, a judge by profession. He was the driving factor behind the establishment of a college in Hyderabad. Dr. Wood landed in Hyderabad, Sindh, on August 24, 1917, after a long journey from Madras. The people of Hyderabad Sindh gave a large sum of money, estimated to be over Rs. 5000/- in less than a week. The donation was quite enough to launch the institute. Dr. Wood, within five weeks, purchased all necessary furniture, books, equipment, etc., and hired the staff to run the institute. The college's location was decided on amid the city's scenic surroundings. Seth Pertab Rai Manghar Singh and a few others contributed their best piece of 64 acres of cultivated land for this beautiful deed. The date of the college's Foundation was chosen to coincide with Dr. Besant's birthday, 1st October 1917. Dr. Wood was appointed its founder Principal. The National Educational Trust provided the initial funding for the college. Later, in 1921, the college was given to the 'Diwan Metharam Darmada Trust', which was run by Diwan Dayaram Gidumal, who provided Rs. 100000/- for the college's affiliation with Bombay University. After Diwan Dayaram Gidumal's death, the college was renamed D. G. National College Hyderabad.
        </p>
        <p>
          The college initially began its journey as intermediate Arts College, soon the courses were offered in B.Sc. in Industrial Science; B. A. in Agriculture and Political Science; and B.Com. In June 1927, B. A. (Hons.) in English, History, Economics and Philosophy were also offered. In 1934, intermediate science classes were also started, which made the college a Science College. In 1940, there was the commencement of M. A. classes in Sindhi Literature. In 1945, classes for B.Sc. were started in Zoology, Botany and Chemistry. Later on, due to political turmoil in the Indian sub-continent, the college was closed. Its faculty and other staff migrated from Hyderabad to other parts of India, leaving behind the institute deserted.
        </p>
        <p>
          The second phase of this historic educational institution began after the establishment of Pakistan. The deserted D. G. National College Hyderabad, due to this voluntary departure of its original owners, was taken over by the Government of Sindh. It decided to reopen it on 21st June 1948 with the same name "D. G. National Government College Hyderabad". Prof. Dr. Adrian Duarte was appointed as its Principal. Dr. Duarte had to rebuild the college again from the ground level. The extraordinary leadership of the appointed Principal was instrumental in the re- birth of this fantastic institute. The re-birth of this glorious institute took place under the remarkable leadership with 224 students on the roll and a faculty comprised of 6 professors, 15 Lecturers and three demonstrators.
        </p>
        <p>
          There was co-education till 1952- as there was no college for the girls. On 9th April 1949, the college was renamed "Government Arts College, Hyderabad". Later, on 7th March 1951, the college was renamed "Government College Hyderabad" through a government resolution and was allowed to teach up to B. Sc. level in affiliation with Sindh University. Within the next few years, there was a significant increase in the number of science students. During the academic session 1952-53, the enrolment surpassed 1000.
        </p>
        <p>
          Government College Hyderabad has the honour of starting post-graduate classes in Arts and Science for the first time after Sindh University was shifted from Karachi to Hyderabad. Its professors were given the status of part- time Professors of the University. The commencement of M. A. (Urdu & English) and M.Sc. (Physics; Chemistry; Mathematics and Statistics) in 1991 and later M.Sc. in Zoology and Botany in 1993 ushered a new era in the history of this institution. Another milestone in the pathway towards success was the commencement of Bachelor of Computer Science (BCS) in 2002. Being one of the oldest institutions of Sindh and with heritage in academic excellence, people of Hyderabad, Alumni and the faculty of this institution looked forward for the up-gradation to the level of university. This demand had its due voice in print and electronic media of Sindh province.
        </p>
        <p>
          The demand towards the up-gradation as University touched its peak when one of its shining stars, Raja Pervez Ashraf, occupied the highest seat of Prime Minister of Islamic Republic of Pakistan. His Excellency, Raja Pervez Ashraf, visited his alma mater on 23rd February 2013. The Alumni and the faculty members of Government College Hyderabad were determined to keep calling the attention of the political, social and educational leadership towards the noble cause of the establishment of Government College University Hyderabad. A delegate of Alumni comprised of Prof. Dr. Nasiruddin Shaikh, Prof. Muhammad Idris Khan, Mr. Abdul Rehman Rajput (Ex MPA), Mr. Mazharul Haq Siddiqui (Ex VC, Sindh University), Mr. Kazi Asad Abid (renowned journalist), met with Excellency Syed Murad Ali Shah, Chief Minister, Sindh. The delegate briefed the Excellency CM about the outstanding contribution of their alma mater in nation-building and services being rendered for almost a century. The representative reiterated the Alumni demand for the up-gradation of Government College Hyderabad to a university. The CM Sindh appreciated the concerns of all Phulalians. The long-awaited day finally arrived. His Excellency, Syed Murad Ali Shah, CM Sindh, officially announced the up-gradation of the status of Government College Hyderabad as University on 9th of October 2017, while presiding over the seminar "Government College Hyderabad: Past, Present, and Future" at the Assembly Hall of Government College Hyderabad. The Sindh Government Gazette notification video, the title "Government College University Hyderabad Act 2018", was issued on 21st May 2018 by the Provincial Assembly of Sindh, thus conferring upon official status to Government College University Hyderabad. The official notification of Prof. Dr. Nasiruddin Shaikh (Principal, Government College Hyderabad) as acting vice chancellor on 13th February 2019. The Chief Minister of Sindh, Syed Murad Ali Shah appointed Prof. Dr. Tayyaba Zarif as the first regular Vice Chancellor of GC University Hyderabad after the recommendations from search committee. She took charge as first founder Vice Chancellor of GC University on 12th March 2021 and leading the ship with new ideas, enthusiasm and motivation to strengthening the university.
        </p>
      </div>
    </div>
  );
}
